server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ruiji
  cache:
    redis:
      time-to-live: 1800000 #秒
  redis:
    database: 0
    port: 6379
    password: 201014
    host: 192.168.107.215
  shardingsphere:
    datasource:
      names:
        master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.137.1:3306/ruiji?characterEncoding=utf-8
        username: root
        password: 201014
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.107.215:3306/ruiji?characterEncoding=utf-8
        username: root
        password: root201014
    masterslave:
      #      从库的配置：轮询
      load-balance-algorithm-type: round_robin
      name: dataSource
      master-data-source-name: master
      slave-data-source-names: slave  #从库名称
    props:
      sql:
        show: true
    #允许bean定义覆盖
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  web:
    resources:
      static-locations: classpath:/static/**
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
ruiji:
  dishimg: /usr/local/ruiji-img
