server:
  port: 8080
spring:
  application:
    name: ruiji
  redis:
    database: 0
    port: 6379
    password: 201014
    host: 192.168.107.214
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 201014
      url: jdbc:mysql://localhost:3306/db_ruiji?serverTimezone=Asia/Shanghai
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  web:
    resources:
      static-locations: classpath:/static/**
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
ruiji:
  dishimg: D:\Ruigi\src\main\resources\static\common\
